steps:
- task: NodeTool@0
  displayName: 'Use Node 10.x'
  inputs:
    versionSpec: 10.x
- task: ShellScript@2
  displayName: 'Build'
  env:
    SYSTEM_BUILDPATH: $(Build.Repository.LocalPath)
  inputs:
    scriptPath: 'build.sh'
