steps:
- task: NodeTool@0
    displayName: 'Use Node 8.x'
    inputs:
      versionSpec: 8.x
- task: ShellScript@2
  displayName: 'Build'
  env:
    SYSTEM_BUILDPATH: $(Build.Repository.LocalPath)
  inputs:
    scriptPath: 'build.sh'
